services:
  - type: web
    name: wolvcapital
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: "bash start.sh"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: DJANGO_SETTINGS_MODULE
        value: "wolvcapital.settings"
      - key: PYTHONPATH
        value: "."
      - key: WEB_CONCURRENCY
        value: "2"
      - key: DATABASE_URL
        fromDatabase:
          name: wolvcapital-db
          property: connectionString

databases:
  - name: wolvcapital-db
    databaseName: wolvcapital
    user: wolvcapital